language: node_js
node_js:
  - "4.2.4"

services:
  - mongodb

before_script:
  - sleep 15
  - "npm install -g gulp"
  - "npm install"
  - "bower install"
  - "cp settings.example.js settings.js"

script: gulp allTests
